### ISSUE TITLE
Use JavaScript Standard Style

### ISSUE THREAD

**Issue by vorg** [vorg/pex-next#2]
Standard https://github.com/feross/standard
- two spaces
- no semicolons
- automatic formatting and checking (via modules)

Example file: https://github.com/feross/bittorrent-dht/blob/master/client.js#L1

**Comment by szymonkaliski** [comment]
@vorg I spoke about this with @automat try this tool: http://jscs.info :)

EDIT: oh, standard is another tool, sorry for rushing with the comment

**Comment by vorg** [comment]
@szymonkaliski It's not irrelevant. It's good to point out a difference between _code style_:
- spaces vs tabs
- space after `function_name_(params)`
- semicolons or not?
- ...

and _library style_
- constants

``` javascript
ConstantValue vs CONSTANT_VALUE
```
- setters `setFoo(value) / getFoo()` vs `foo(value) / foo()`
- chaining
- `opts` objects
- callbacks vs promises
- factory methods `createShader` vs OOP `new Shader()`
- ...

For example: [Node Style Guide](https://github.com/felixge/node-style-guide#use-uppercase-for-constants)

EDIT: Added example style guide

**Comment by automat** [comment]
General question: how strict should a pex styleguide be?  I definitely see a need for a set of rules when writing pex modules, but im not sure how rigid it should be for other projects using pex. Is it defining a minimal basic set of rules leaving room for personal preferences? So, library vs code style.

Some thoughts on things already mentioned.
- spaces vs tabs, i personally find it hard and confusing to work with 2 spaces because everything looks like a huge single chunk, the overall structure is not clear enough. I could move to use 2 spaces in pex modules, but for projects in general i would still stick with tabs. So this is related to how rigid this guide should be.
- semicolons!. Non semicolons is error-prone. eg. closure after function
- recognizable getters and setters 
  
  ```
  setFoo(value);
  getFoo(out);
  enableFoo(enable);
  isEnabled();
  hasProperty();
  ```
- chaining 
  
  ```
  //I like chaining in primitives
  color.setRGB(r,g,b).setHSVValue(25);
  //but also in those cases 
  program
      .bind()
      .uniform1f('uAlpha',1.0)
      .uniformMatrix4fv('uGlobalTranslationMatrix',matrix)
      .uniform1i('uTexture',1)
      .uniform2f('uSize,100,200)
      .uniform4f('uRect',0,-100,10,10);
  //espeaciilly in geom primitives
  aabb0.set(aabb1).include(aabb2).normalizePointsf(points,1)
  //but not as a general feature
  ```
- `opts`objects, in terms of performance i would advice to discard it for everything thats performance intensive, http://jsperf.com/obj-arg-vs-args, basically to avoid object recreation on runtime. I think it might be good to think about this also in terms of function documentations. A descriptive set of arguments might in a lot of cases be more informative.
- factory methods for simple object creation, why? I saw a lot of `Color.create(0,0,0,1)`, `Vec3.create(1,1,1)`, whats the benifit here if it is a proper object? I mean yes if those are arrays ok, but why `Program.create()`
- public vs private

Those things are already too specific. Maybe it also helps if we all prepare an overview or sketch of a possible pex style-guide.

**Comment by vorg** [comment]
@automat i think we should just create a new folder and couple of well commented files representing typical use cases each

**Comment by automat** [comment]
@vorg agreed
